
import com.mashape.unirest.http.HttpResponse;
import com.mashape.unirest.http.Unirest;
import com.mashape.unirest.http.exceptions.UnirestException;
import com.teamdev.jxbrowser.browser.Browser;
import com.teamdev.jxbrowser.engine.Engine;
import com.teamdev.jxbrowser.engine.EngineOptions;
import static com.teamdev.jxbrowser.engine.RenderingMode.HARDWARE_ACCELERATED;
import com.teamdev.jxbrowser.navigation.event.NavigationStarted;
import com.teamdev.jxbrowser.view.swing.BrowserView;
import java.awt.BorderLayout;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.WindowConstants;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author gupta's
 */
public class confirmbooking extends javax.swing.JFrame {

    /**
     * Creates new form confirmbooking
     */
    
    int rent,carid;
    String radio,security;
            long getdays;
            
            
            String name;
            String phone;
            String address;
            String email;
            String startdate ;
            String enddate;
            String status = "active";
    public confirmbooking(int carid, String radio , Date d , Date d2 , long getdays , String security) {
        initComponents();
        setVisible(true);
        setSize(600,1000);
        setTitle("Confirm Booking");
        this.carid=carid;
        this.radio=radio;
        this.security=security;
        this.getdays=getdays;
        
        
        int priceperday = Integer.parseInt(radio);
        jTextField1.setText(radio);
        jTextField6.setText(security);
        jTextField4.setText(getdays+"");
        
        int m1 = d.getMonth()+1;
        int m2 = d2.getMonth()+1;
        
        
        int y1 = d.getYear()+1900;
        int y2 = d2.getYear()+1900;
//        int date1 = d.getDate();
        jTextField2.setText(d.getDate()+"/"+m1+"/"+y1);
        jTextField3.setText(d2.getDate()+"/"+m2+"/"+y2);
       rent = (int) (priceperday * getdays);
       jTextField5.setText(rent+"");
       
       
       
       
        
        System.out.println(d.getDay()+"/"+d.getMonth()+1+"/"+d.getYear()+1900);
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Price Per Day");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(40, 70, 110, 20);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Start Date");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 120, 70, 14);

        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(132, 137, 34, 0);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("End Date");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(40, 170, 70, 14);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("No Of Days");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(40, 220, 70, 15);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Rent");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(40, 270, 30, 15);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Security");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(40, 320, 50, 14);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Name");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(40, 370, 34, 15);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Phone No.");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(40, 420, 70, 15);

        jTextField1.setEditable(false);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(180, 70, 140, 20);

        jTextField2.setEditable(false);
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField2);
        jTextField2.setBounds(180, 120, 140, 20);

        jTextField3.setEditable(false);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(180, 170, 140, 20);

        jTextField4.setEditable(false);
        getContentPane().add(jTextField4);
        jTextField4.setBounds(180, 220, 140, 20);

        jTextField5.setEditable(false);
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField5);
        jTextField5.setBounds(180, 270, 140, 20);

        jTextField6.setEditable(false);
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField6);
        jTextField6.setBounds(180, 320, 140, 20);
        getContentPane().add(jTextField7);
        jTextField7.setBounds(180, 370, 140, 20);

        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField8);
        jTextField8.setBounds(180, 420, 140, 20);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("SUBMIT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(160, 680, 100, 40);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Email");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(40, 470, 40, 14);
        getContentPane().add(jTextField9);
        jTextField9.setBounds(180, 470, 140, 20);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Address");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(40, 520, 60, 20);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(180, 510, 140, 130);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
             name=jTextField7.getText();
             phone=jTextField8.getText();
            address=jTextArea1.getText();
            email=jTextField9.getText();
           startdate = jTextField2.getText();
           enddate = jTextField3.getText();
          
            ////payment
      EngineOptions options =EngineOptions.newBuilder(HARDWARE_ACCELERATED)
                .licenseKey("1BNDJDKIKHQKD11INO3EIYTKYJWXR00G9QHQLR4CCQ221LX62PL1M1MDIV4EM01V3DXCSD").build();
        Engine engine = Engine.newInstance(options);
        Browser browser = engine.newBrowser();
         SwingUtilities.invokeLater(() -> {
             BrowserView view = BrowserView.newInstance(browser);
             JFrame frame = new JFrame("payment demo");
             frame.addWindowListener(new WindowAdapter() {
                 public void windowClosing(WindowEvent e)
                 {
                     System.out.println("engine closed");
                    engine.close();
                 }
                 });
             frame.setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
             int amount =12345;
             browser.navigation().on(NavigationStarted.class,event ->{
                 String url = event.url();
                 System.out.println("url:"+url);
                 if(url.contains("BookingSuccess.html"))
                 {
                     String ss = url.substring(url.indexOf("?")+1);
                     String id = ss.substring(ss.indexOf("=")+1);
//     
//JOptionPane.showMessageDialog(rootPane, id);

                     frame.dispose();
                     sendtodb();
                 }
             });
             browser.navigation().loadUrl("http://amrinder.vmm.education/paymentdemo.html?amount="+rent+"&name=cab_payment&desc=Car&photo=https://images-na.ssl-images-amazon.com/images/I/661yMQIMMODL._SY606_.jpg");
             frame.add(view,BorderLayout.CENTER);
             frame.setSize(1000, 700);
             frame.setLocationRelativeTo(null);
             frame.setVisible(true);
         });
     
     
     
     
     ///////
//     sendtodb();
 
            
        } catch (Exception ex) {
            Logger.getLogger(confirmbooking.class.getName()).log(Level.SEVERE, null, ex);
        }


               
               
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(confirmbooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(confirmbooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(confirmbooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(confirmbooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
              //  new confirmbooking().setVisible(true);
            }
        });
    }
    
    void sendtodb(){
          
        try {
            HttpResponse<String> obj= Unirest.get("http://localhost:8888/ConfirmBooking").queryString("carid",carid).queryString("radio",radio)
                    .queryString("startdate",startdate).queryString("enddate",enddate).queryString("getdays",getdays)                .queryString("startdate",startdate).queryString("enddate",enddate).queryString("getdays",getdays)
                    .queryString("rent",rent).queryString("security",security).queryString("name",name)
                    .queryString("status",status)
                    .queryString("phone",phone).queryString("address",address).queryString("email",email).asString();
            
            if(obj.getStatus() == 200){
                try {
                                    JOptionPane.showMessageDialog(rootPane, obj.getBody());
                    
                    HttpResponse<String> res2 = Unirest.get("http://server1.vmm.education/VMMCloudMessaging/AWS_SMS_Sender")
                            .queryString("username","danishbhola")
                            .queryString("password","8THBFZ7K")
                            .queryString("message","Booking confirmed")
                            .queryString("phone_numbers",phone).asString();
                    
                    if(res2.getStatus() == 200)
                    {
                        System.out.println(res2.getBody());
                    }
                } catch (UnirestException ex) {
                    Logger.getLogger(confirmbooking.class.getName()).log(Level.SEVERE, null, ex);
                }
                
                
                
                
                
            }
        } catch (UnirestException ex) {
            Logger.getLogger(confirmbooking.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
