
import com.mashape.unirest.http.HttpResponse;
import com.mashape.unirest.http.Unirest;
import com.mashape.unirest.http.exceptions.UnirestException;
import java.awt.Dimension;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.Toolkit;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.image.BufferedImage;
import java.io.BufferedReader;
import java.net.URL;
import java.util.StringTokenizer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Gurpreet Singh
 */
public final class userhome extends javax.swing.JFrame {
String uname;
    
    public userhome(String uname) throws UnirestException {
        this.uname=uname;
        initComponents();
        
        Dimension dm=Toolkit.getDefaultToolkit().getScreenSize();
        int height=dm.height;
        int width=dm.width;
        lb2.setText(uname);
        jp2.setBounds(10, 120, 165, height);
        jp1.setBounds(10, 10, 1330,100);
        jScrollPane2.setBounds(180, 120, width-200, height);
        setSize(width,height);
         getdata();
        setVisible(true);
        setTitle("User Home");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jp1 = new javax.swing.JPanel();
        lb1 = new javax.swing.JLabel();
        lb2 = new javax.swing.JLabel();
        bt1 = new javax.swing.JButton();
        bt8 = new javax.swing.JButton();
        jp2 = new javax.swing.JPanel();
        bt2 = new javax.swing.JButton();
        bt3 = new javax.swing.JButton();
        bt4 = new javax.swing.JButton();
        bt5 = new javax.swing.JButton();
        bt6 = new javax.swing.JButton();
        bt7 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jp1.setBackground(new java.awt.Color(255, 204, 204));
        jp1.setLayout(null);

        lb1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lb1.setText("WELCOME :");
        jp1.add(lb1);
        lb1.setBounds(260, 10, 90, 30);

        lb2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lb2.setForeground(new java.awt.Color(51, 51, 255));
        jp1.add(lb2);
        lb2.setBounds(350, 10, 140, 30);

        bt1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bt1.setIcon(new javax.swing.ImageIcon("C:\\Users\\gupta's\\Documents\\NetBeansProjects\\cabbooking 2\\cabbooking 2\\src\\photos\\change.png")); // NOI18N
        bt1.setText("Change Password");
        bt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt1ActionPerformed(evt);
            }
        });
        jp1.add(bt1);
        bt1.setBounds(530, 50, 180, 40);

        bt8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bt8.setIcon(new javax.swing.ImageIcon("C:\\Users\\gupta's\\Documents\\NetBeansProjects\\cabbooking 2\\cabbooking 2\\src\\photos\\mybookings.png")); // NOI18N
        bt8.setText("My Bookings");
        bt8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt8ActionPerformed(evt);
            }
        });
        jp1.add(bt8);
        bt8.setBounds(530, 3, 180, 40);

        getContentPane().add(jp1);
        jp1.setBounds(10, 10, 740, 100);

        jp2.setBackground(new java.awt.Color(255, 204, 204));
        jp2.setLayout(null);

        bt2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bt2.setText("All");
        bt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt2ActionPerformed(evt);
            }
        });
        jp2.add(bt2);
        bt2.setBounds(40, 30, 80, 30);

        bt3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bt3.setText("Sedan");
        bt3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt3ActionPerformed(evt);
            }
        });
        jp2.add(bt3);
        bt3.setBounds(40, 80, 80, 30);

        bt4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bt4.setText("Coupe");
        bt4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt4ActionPerformed(evt);
            }
        });
        jp2.add(bt4);
        bt4.setBounds(40, 200, 80, 30);

        bt5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bt5.setText("SUV");
        bt5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt5ActionPerformed(evt);
            }
        });
        jp2.add(bt5);
        bt5.setBounds(40, 260, 80, 30);

        bt6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bt6.setText("XUV");
        bt6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt6ActionPerformed(evt);
            }
        });
        jp2.add(bt6);
        bt6.setBounds(40, 140, 80, 30);

        bt7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bt7.setText("Convertible");
        bt7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt7ActionPerformed(evt);
            }
        });
        jp2.add(bt7);
        bt7.setBounds(30, 320, 110, 30);

        getContentPane().add(jp2);
        jp2.setBounds(10, 120, 160, 380);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(2000, 2000));
        jPanel1.setLayout(null);
        jScrollPane2.setViewportView(jPanel1);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(160, 120, 570, 380);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt1ActionPerformed
       changepassworduser obj=new changepassworduser(uname);
    }//GEN-LAST:event_bt1ActionPerformed

    private void bt5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt5ActionPerformed
 searchbytype("SUV");        // TODO add your handling code here:
    }//GEN-LAST:event_bt5ActionPerformed

    private void bt6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt6ActionPerformed
 searchbytype("XUV");        
    }//GEN-LAST:event_bt6ActionPerformed

    private void bt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt2ActionPerformed
       getdata();
    }//GEN-LAST:event_bt2ActionPerformed

    private void bt3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt3ActionPerformed
      
        searchbytype("Sedan");
    }//GEN-LAST:event_bt3ActionPerformed

    private void bt4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt4ActionPerformed
 searchbytype("Coupe");        // TODO add your handling code here:
    }//GEN-LAST:event_bt4ActionPerformed

    private void bt7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt7ActionPerformed
 searchbytype("Convertible");        // TODO add your handling code here:
    }//GEN-LAST:event_bt7ActionPerformed

    private void bt8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt8ActionPerformed
       mybookings obj=new mybookings();
    }//GEN-LAST:event_bt8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(userhome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(userhome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(userhome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(userhome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
               // new userhome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt1;
    private javax.swing.JButton bt2;
    private javax.swing.JButton bt3;
    private javax.swing.JButton bt4;
    private javax.swing.JButton bt5;
    private javax.swing.JButton bt6;
    private javax.swing.JButton bt7;
    private javax.swing.JButton bt8;
    public javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel jp1;
    private javax.swing.JPanel jp2;
    private javax.swing.JLabel lb1;
    private javax.swing.JLabel lb2;
    // End of variables declaration//GEN-END:variables


 void getdata() 
{
    try {
        HttpResponse<String> httpobj = Unirest.get("http://localhost:8888/getcardata").asString();
        
        if(httpobj.getStatus()==200)
        {
            String jt=httpobj.getBody();
            System.out.println(jt);
            
            StringTokenizer st1 = new StringTokenizer(jt,"~");
            int count = st1.countTokens();
            int x=10;
            int y=10;
            int i=0;
            
            smallpanel pd[]=new smallpanel[count] ;
            while(st1.hasMoreTokens())
            {
                pd[i] = new smallpanel();
                String st2 = st1.nextToken();
                StringTokenizer st3 = new StringTokenizer(st2,";");
                int carid = Integer.parseInt(st3.nextToken());
                String cname=st3.nextToken();
                String bname=st3.nextToken();
                
                String ctype=st3.nextToken();
                String ftype=st3.nextToken();
                String woutd = (st3.nextToken());
                String wd =(st3.nextToken());
                String security = (st3.nextToken());
                String photo=st3.nextToken();
                System.out.println(ctype+","+security);
                
                pd[i].setBounds(x, y, 1140, 150);
                y = y+170;
                pd[i].lb2.setText(bname);
                pd[i].lb3.setText(ctype);
                //// image
                
                 try {
                URL url = new URL("http://localhost:8888/GetResource/" + photo);
                     BufferedImage bufferedImage = ImageIO.read(url);
              BufferedImage  newimage = resize(bufferedImage, 100, 100);
               pd[i].lb1.setIcon(new ImageIcon(newimage));
                     
            } catch (Exception ex) {
                ex.printStackTrace();
            }
                
              pd[i].addMouseListener(new MouseAdapter() {
                    @Override
                    public void mouseClicked(MouseEvent e) {
                        super.mouseClicked(e); //To change body of generated methods, choose Tools | Templates.
                        bookcar obj=new bookcar(carid,cname,woutd,wd,security,photo);
                    }
                  
                  
}); 
                
                
               
                pd[i].lb4.setText(wd);
                pd[i].lb5.setText(woutd);
//                
                jPanel1.add(pd[i]);
                repaint();
                pd[i].repaint();
                repaint();
                jPanel1.repaint();
                
                i++; }
            
        }   } catch (UnirestException ex) {
        Logger.getLogger(userhome.class.getName()).log(Level.SEVERE, null, ex);
    }




}
 
 
 void searchbytype(String ab)
 {
    try {
        HttpResponse<String> httpobj = Unirest.get("http://localhost:8888/searchbytype").queryString("cartype",ab).asString();
        
        if(httpobj.getStatus()==200)
        {
             String jt=httpobj.getBody();
            System.out.println(jt);
            
            StringTokenizer st1 = new StringTokenizer(jt,"~");
            int count = st1.countTokens();
            int x=10;
            int y=10;
            int i=0;
            jPanel1.removeAll();
            smallpanel pd[]=new smallpanel[count] ;
            while(st1.hasMoreTokens())
            {
                pd[i] = new smallpanel();
                String st2 = st1.nextToken();
                StringTokenizer st3 = new StringTokenizer(st2,";");
                int carid = Integer.parseInt(st3.nextToken());
                String cname=st3.nextToken();
                String bname=st3.nextToken();
                
                String ctype=st3.nextToken();
                String ftype=st3.nextToken();
                String woutd = (st3.nextToken());
                String wd =(st3.nextToken());
                String security = (st3.nextToken());
                String photo=st3.nextToken();
                System.out.println(ctype+","+security);
                
                pd[i].setBounds(x, y, 1140, 150);
                y = y+170;
                pd[i].lb2.setText(bname);
                pd[i].lb3.setText(ctype);
                
                
                
                    
              pd[i].addMouseListener(new MouseAdapter() {
                    @Override
                    public void mouseClicked(MouseEvent e) {
                        super.mouseClicked(e); //To change body of generated methods, choose Tools | Templates.
                        bookcar obj=new bookcar(carid,cname,woutd,wd,security,photo);
                    }
                  
                  
}); 
                
                 try {
                URL url = new URL("http://localhost:8888/GetResource/" + photo);
                     BufferedImage bufferedImage = ImageIO.read(url);
              BufferedImage  newimage = resize(bufferedImage, 100, 100);
               pd[i].lb1.setIcon(new ImageIcon(newimage));
                     
            } catch (Exception ex) {
                ex.printStackTrace();
            }
                pd[i].lb4.setText(wd);
                pd[i].lb5.setText(woutd);
//                
                jPanel1.add(pd[i]);
                repaint();
                pd[i].repaint();
                repaint();
                jPanel1.repaint();
                
                i++;
        }}
        else
        {
            jPanel1.removeAll();
        }
    } 
     catch (UnirestException ex) {
        Logger.getLogger(userhome.class.getName()).log(Level.SEVERE, null, ex);
    }
        
 }
 
 
 BufferedImage resize(BufferedImage image, int width, int height) {
        BufferedImage bi = new BufferedImage(width, height, BufferedImage.TRANSLUCENT);
        Graphics2D g2d = (Graphics2D) bi.createGraphics();
        g2d.addRenderingHints(new RenderingHints(RenderingHints.KEY_RENDERING, RenderingHints.VALUE_RENDER_QUALITY));
        g2d.drawImage(image, 0, 0, width, height, null);
        g2d.dispose();
        return bi;
    }

}
